(*
 * File:            enabling-test.sml
 * Generation date: Mon Aug 12 07:57:29 2013
 *
 * Run-time checks: true
 *)

structure DveEnablingTest = struct

open DveDefinitions

fun isEnabledLOC_0_P_bloodmri_start_T_begin_TO_end ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_start_S = P_bloodmri_start_STATE_begin)
fun isEnabledLOC_1_P_bloodmri_initial_evaluation_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_initial_evaluation_S = P_bloodmri_initial_evaluation_STATE_tr andalso 0 <> (if (GV_bloodmri_start_suc) > (0) then 1 else 0))
fun isEnabledLOC_2_P_bloodmri_blood_test_1_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_blood_test_1_S = P_bloodmri_blood_test_1_STATE_tr andalso 0 <> (if (GV_bloodmri_initial_evaluation_suc_0) > (0) then 1 else 0))
fun isEnabledLOC_3_P_bloodmri_join_6_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_join_6_S = P_bloodmri_join_6_STATE_tr andalso 0 <> (Word.toInt (Word.andb (Word.fromInt (if (GV_bloodmri_blood_test_1_suc) > (0) then 1 else 0), Word.fromInt (if (GV_bloodmri_mri_suc) > (0) then 1 else 0)))))
fun isEnabledLOC_4_P_bloodmri_evaluation_1_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_evaluation_1_S = P_bloodmri_evaluation_1_STATE_tr andalso 0 <> (if (GV_bloodmri_join_6_suc) > (0) then 1 else 0))
fun isEnabledLOC_5_P_bloodmri_evaluation_1_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_evaluation_1_S = P_bloodmri_evaluation_1_STATE_tr andalso 0 <> (if (GV_bloodmri_join_6_suc) > (0) then 1 else 0))
fun isEnabledLOC_6_P_bloodmri_procedure_a_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_procedure_a_S = P_bloodmri_procedure_a_STATE_tr andalso 0 <> (if (GV_bloodmri_evaluation_1_suc_0) > (0) then 1 else 0))
fun isEnabledLOC_7_P_bloodmri_join_10_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_join_10_S = P_bloodmri_join_10_STATE_tr andalso 0 <> (if (GV_bloodmri_procedure_a_suc) > (0) then 1 else 0))
fun isEnabledLOC_8_P_bloodmri_join_10_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_join_10_S = P_bloodmri_join_10_STATE_tr andalso 0 <> (if (GV_bloodmri_procedure_b_suc) > (0) then 1 else 0))
fun isEnabledLOC_9_P_bloodmri_loop_14_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_loop_14_S = P_bloodmri_loop_14_STATE_tr andalso 0 <> (if (GV_bloodmri_join_10_suc) > (0) then 1 else 0))
fun isEnabledLOC_10_P_bloodmri_loop_14_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_loop_14_S = P_bloodmri_loop_14_STATE_tr andalso 0 <> (if (GV_bloodmri_loopc_13_suc_1) > (0) then 1 else 0))
fun isEnabledLOC_11_P_bloodmri_take_test_drug_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_take_test_drug_S = P_bloodmri_take_test_drug_STATE_tr andalso 0 <> (if (GV_bloodmri_loop_14_suc) > (0) then 1 else 0))
fun isEnabledLOC_12_P_bloodmri_blood_test_2_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_blood_test_2_S = P_bloodmri_blood_test_2_STATE_tr andalso 0 <> (if (GV_bloodmri_take_test_drug_suc) > (0) then 1 else 0))
fun isEnabledLOC_13_P_bloodmri_loopc_13_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_loopc_13_S = P_bloodmri_loopc_13_STATE_tr andalso 0 <> (if (GV_bloodmri_blood_test_2_suc) > (0) then 1 else 0))
fun isEnabledLOC_14_P_bloodmri_final_evaluation_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_final_evaluation_S = P_bloodmri_final_evaluation_STATE_tr andalso 0 <> (if (GV_bloodmri_loopc_13_suc_0) > (0) then 1 else 0))
fun isEnabledLOC_15_P_bloodmri_outputcondition_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_outputcondition_S = P_bloodmri_outputcondition_STATE_tr andalso 0 <> (if (GV_bloodmri_final_evaluation_suc) > (0) then 1 else 0))
fun isEnabledLOC_16_P_bloodmri_procedure_b_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_procedure_b_S = P_bloodmri_procedure_b_STATE_tr andalso 0 <> (if (GV_bloodmri_evaluation_1_suc_1) > (0) then 1 else 0))
fun isEnabledLOC_17_P_bloodmri_mri_T_tr_TO_tr ({ GV_workflow_composition_ok, GV_bloodmri_start_suc, GV_bloodmri_initial_evaluation_suc_0, GV_bloodmri_initial_evaluation_suc_1, GV_bloodmri_blood_test_1_suc, GV_bloodmri_join_6_suc, GV_bloodmri_evaluation_1_suc_0, GV_bloodmri_evaluation_1_suc_1, GV_bloodmri_procedure_a_suc, GV_bloodmri_join_10_suc, GV_bloodmri_loop_14_suc, GV_bloodmri_take_test_drug_suc, GV_bloodmri_blood_test_2_suc, GV_bloodmri_loopc_13_suc_0, GV_bloodmri_loopc_13_suc_1, GV_bloodmri_final_evaluation_suc, GV_bloodmri_outputcondition_suc, GV_bloodmri_procedure_b_suc, GV_bloodmri_mri_suc, GV_bloodmri_loop1counter, P_bloodmri_start_S, P_bloodmri_initial_evaluation_S, P_bloodmri_blood_test_1_S, P_bloodmri_join_6_S, P_bloodmri_evaluation_1_S, P_bloodmri_procedure_a_S, P_bloodmri_join_10_S, P_bloodmri_loop_14_S, P_bloodmri_take_test_drug_S, P_bloodmri_blood_test_2_S, P_bloodmri_loopc_13_S, P_bloodmri_final_evaluation_S, P_bloodmri_outputcondition_S, P_bloodmri_procedure_b_S, P_bloodmri_mri_S }: state) =
   (P_bloodmri_mri_S = P_bloodmri_mri_STATE_tr andalso 0 <> (if (GV_bloodmri_initial_evaluation_suc_1) > (0) then 1 else 0))
fun getEnabledEvents (st: state) = let
   val l = ref []
in
   if isEnabledLOC_17_P_bloodmri_mri_T_tr_TO_tr st then l := LOC_17_P_bloodmri_mri_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_16_P_bloodmri_procedure_b_T_tr_TO_tr st then l := LOC_16_P_bloodmri_procedure_b_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_15_P_bloodmri_outputcondition_T_tr_TO_tr st then l := LOC_15_P_bloodmri_outputcondition_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_14_P_bloodmri_final_evaluation_T_tr_TO_tr st then l := LOC_14_P_bloodmri_final_evaluation_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_13_P_bloodmri_loopc_13_T_tr_TO_tr st then l := LOC_13_P_bloodmri_loopc_13_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_12_P_bloodmri_blood_test_2_T_tr_TO_tr st then l := LOC_12_P_bloodmri_blood_test_2_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_11_P_bloodmri_take_test_drug_T_tr_TO_tr st then l := LOC_11_P_bloodmri_take_test_drug_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_10_P_bloodmri_loop_14_T_tr_TO_tr st then l := LOC_10_P_bloodmri_loop_14_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_9_P_bloodmri_loop_14_T_tr_TO_tr st then l := LOC_9_P_bloodmri_loop_14_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_8_P_bloodmri_join_10_T_tr_TO_tr st then l := LOC_8_P_bloodmri_join_10_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_7_P_bloodmri_join_10_T_tr_TO_tr st then l := LOC_7_P_bloodmri_join_10_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_6_P_bloodmri_procedure_a_T_tr_TO_tr st then l := LOC_6_P_bloodmri_procedure_a_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_5_P_bloodmri_evaluation_1_T_tr_TO_tr st then l := LOC_5_P_bloodmri_evaluation_1_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_4_P_bloodmri_evaluation_1_T_tr_TO_tr st then l := LOC_4_P_bloodmri_evaluation_1_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_3_P_bloodmri_join_6_T_tr_TO_tr st then l := LOC_3_P_bloodmri_join_6_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_2_P_bloodmri_blood_test_1_T_tr_TO_tr st then l := LOC_2_P_bloodmri_blood_test_1_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_1_P_bloodmri_initial_evaluation_T_tr_TO_tr st then l := LOC_1_P_bloodmri_initial_evaluation_T_tr_TO_tr :: !l else ();
   if isEnabledLOC_0_P_bloodmri_start_T_begin_TO_end st then l := LOC_0_P_bloodmri_start_T_begin_TO_end :: !l else ();
   !l
end
end
